plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.144'
}

group = 'cz.lucie.flightring'
version = '1.2.0'

base {
    archivesName = 'flightring'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    // Curios API
    maven { url = 'https://maven.theillusivec4.top/' }
}

neoForge {
    version = '21.1.235'

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        flightring {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation 'top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1'
}

jar {
    manifest {
        attributes([
            'Specification-Title'   : 'flightring',
            'Implementation-Title'  : 'Flight Ring',
            'Implementation-Version': project.version
        ])
    }
}
